first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name = 'user_login'),
]

first_project/first_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from first_app import views
from django.conf.urls import include


urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^first_app/', include('first_app.urls')),
    url(r'^formpage/', views.form_view, name = 'form_name'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special'),

]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique = True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic)
    name = models.CharField(max_length=264, unique=True)
    url  = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage)
    date = models.DateField()

    def __str__(self):
        return str(self.date)



class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo



def check_for_z(value):
    if value[0].lower()!='z':
        raise forms.ValidationError("Names Need to Start with Z")

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label = "Enter your email again")
    text = forms.CharField(widget=forms.Textarea)


    """
    botcatcher = forms.CharField(required =  False,
                                widget = forms.HiddenInput,
                                validators = [validators.MaxLengthValidator(0)])
    """

    """
    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError("GOTCHA BOT")
        return botcatcher
    """

    def clean(self):
        all_clean_data  = super().clean()
        email = all_clean_data['email']
        verify_email = all_clean_data['verify_email']

        if email != verify_email:
            raise forms.ValidationError("Make sure emails match")



class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
            model = User
            fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic, Webpage, AccessRecord
from first_app.forms import UserForm, UserProfileInfoForm
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout


# Create your views here.

def index(request):
    """
    webpage_list =  AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpage_list}
    """
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'first_app/test.html', context = context_dict)


def form_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDAION SUCCESS")
            print(form.cleaned_data['name'])
            print(form.cleaned_data['text'])

    return render(request, 'first_app/form_page.html',{'form': form} )


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice")


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered=True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'first_app/registration.html',
                    {'user_form': user_form,
                    'profile_form': profile_form,
                    'registered': registered})



def user_login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("your Account isn't active")

        else:
            print("Someone tried to login")
            return HttpResponse("invalid Login Details Supplied")

    else:
        return render(request, 'first_app/login.html',{})

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul clsss="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}"> Home</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}"> Admin</a> </li>
          <li> <a class = "navbar-link" href="{% url 'first_app:register' %}"> Register</a> </li>

          {% if user.is_authenticated %}
          <li><a class = "navbar-link" href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
          <li> <a class = "navbar-link" href="{% url 'first_app:user_login' %}">Login</a> </li>
          {% endif %}
        </ul>

      </div>

    </nav>

    <div class="container">


    {% block body_block %}
    <!-- anything outside of this will be extended -->
    {% endblock %}
    </div>
  </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1>Fill the form</h1>
      <form method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="Submit" class = "btn btn-primary" name="" value="Submit">
      </form>

    </div>
  </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Level 2</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/test.css" %}">
  </head>
  <body>
    <h1> <a href="{% url 'first_app:index' %}">Click</a> </h1>
    <h1> <a href="{% url 'admin:index' %}">Go to Admin</a> </h1>
<h1>hi Wlcome to Django Level Two</h1>
<h1>Go to /formpage for fillings forms</h1>
<h2>Here are your access records</h2>
<div class="container">
  <div class="jumbotron">


  {% if access_records %}
  <table>
    <thead>
      <th>Site Name</th>
      <th>Date Accessed</th>
    </thead>

    {% for acc in access_records %}
    <tr>
      <td>{{ acc.name }}</td>
      <td>{{ acc.date }}</td>
    </tr>

    {%  endfor %}
  </table>

  {% else %}
  <p>NO ACCESS Records Found</p>

  {% endif %}


</div>
</div>
  </body>
</html>

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'first_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username: </label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password"> Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>

</div>
{% endblock %}

first_project/templates/first_app/registration.html
{% extends 'first_app/base.html' %}
{% load staticfiles %}


{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank You</h1>
  {% else %}
    <h1>Register</h1>
    <h3>Fill out the form</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}

first_project/templates/first_app/test.html
{% extends "first_app/base.html" %}
{% load my_extras %}

  {% block body_block %}
    <h1>Welcome to test</h1>
    <h2>This is the test page showing</h2>
    <h1>{{ text|cat:"hello" }}
    {{ number|add:"99" }}</h1>
  {% endblock %}